-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 06:18:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CrawlerHost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CrawlerHost` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL DEFAULT NOW(),
  `host` VARCHAR(255) NOT NULL,
  `crawled` DATETIME NULL COMMENT 'The last time the crawler has tried to receive data from the host',
  `crawled_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Counter for how often data has been tried to be accessed from this host',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `domain_UNIQUE` (`host` ASC),
  INDEX `idx_created` (`created` ASC),
  INDEX `idx_updated` (`crawled` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CrawlerTask`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CrawlerTask` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL DEFAULT NOW(),
  `priority` VARCHAR(12) NOT NULL DEFAULT 'normal' COMMENT 'priorities are defined in the configuration',
  `type` ENUM('get', 'post') NOT NULL,
  `url` VARCHAR(255) NOT NULL COMMENT 'full url including the host and protocol',
  `host_id` INT UNSIGNED NOT NULL,
  `data` BLOB NULL COMMENT 'post data which gets attached to the request',
  `file` VARCHAR(16) NULL COMMENT 'name of the downloaded file for the destination directory',
  `downloaded` DATETIME NULL COMMENT 'when the file has been successfully downloaded',
  `failed` DATETIME NULL COMMENT 'last time the task has failed',
  `failed_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'counter for how often downloading the file failed',
  `imported` DATETIME NULL COMMENT 'when the task has been successfully imported',
  `failed_import` DATETIME NULL COMMENT 'an optional field for devs. Store the last time the import of the downloaded file failed',
  `failed_import_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'optional field - counter for how often the import of the downloaded file failed',
  `locked` DATETIME NULL COMMENT 'locked tasks should be ignored since the crawler is processing the task',
  `prioritized_task_id` INT UNSIGNED NULL COMMENT 'the given task has to be downloaded before this task will be executed',
  PRIMARY KEY (`id`),
  INDEX `fk_Crawler_CrawlerDomain1_idx` (`host_id` ASC),
  INDEX `idx_imported` (`imported` ASC),
  INDEX `idx_created` (`created` ASC),
  INDEX `idx_priority` (`priority` ASC),
  INDEX `idx_failed` (`failed` ASC),
  INDEX `idx_failed_import` (`failed_import` ASC),
  INDEX `idx_downloaded` (`downloaded` ASC),
  INDEX `fk_CrawlerTask_CrawlerTask1_idx` (`prioritized_task_id` ASC),
  CONSTRAINT `fk_Crawler_CrawlerDomain1`
    FOREIGN KEY (`host_id`)
    REFERENCES `mydb`.`CrawlerHost` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CrawlerTask_CrawlerTask1`
    FOREIGN KEY (`prioritized_task_id`)
    REFERENCES `mydb`.`CrawlerTask` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CrawlerMeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CrawlerMeta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL DEFAULT NOW(),
  `name` VARCHAR(32) NOT NULL,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `fulltext_name` (`name` ASC),
  INDEX `created_idx` (`created` ASC),
  UNIQUE INDEX `name_value_unique` (`value` ASC, `name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CrawlerTask_Meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CrawlerTask_Meta` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `meta_id` INT UNSIGNED NOT NULL,
  `task_id` INT UNSIGNED NOT NULL,
  INDEX `fk_table1_CrawlerCategory1_idx` (`meta_id` ASC),
  INDEX `fk_table1_Crawler1_idx` (`task_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `category_id_UNIQUE` (`meta_id` ASC, `task_id` ASC),
  CONSTRAINT `fk_table1_CrawlerCategory1`
    FOREIGN KEY (`meta_id`)
    REFERENCES `mydb`.`CrawlerMeta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_table1_Crawler1`
    FOREIGN KEY (`task_id`)
    REFERENCES `mydb`.`CrawlerTask` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
